# Generated by Django 5.1.1 on 2025-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
